services:
  db:
    image: postgres:latest
    restart: unless-stopped
    env_file: .env
    volumes:
      - films-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  bot:
    build: .
    env_file: .env
    restart: unless-stopped

volumes:
  films-db-data:

